import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ display: "flex", flexDirection: "column" }}>
        <div style={{ flexGrow: 1, backgroundColor: "orange", padding: 12 }}>
          <Link href="/">Posts</Link> |
          <Link href="/authors">Authors</Link>

        </div>
        <main style={{ flexGrow: 20, height: "90vh", padding: 12 }}>{children}</main>
        <div style={{ flexGrow: 1, backgroundColor: "lightgrey", padding: 12 }}>footer</div>
      </body>
    </html>
  );
}
