////// regular and arrow functions...

//////// dynamic typing...

///////// truthy values and ===

///////// single thread, heavy process blocks....

///////// Promise

////////// understand the task queue and event loop...
